- hosts: local
  gather_facts: no
  become: yes
  vars_prompt:
  - name: "sudo_pass"
    prompt: "Enter sudo password"
    unsafe: yes
    private: yes
  vars:
    ansible_become_password: "{{ sudo_pass }}"
  tasks:
    - name: Install Squid
      apt:
        name: squid
        update_cache: yes

    - name: Configure Squid
      copy:
        src: "{{ playbook_dir }}/files/squid.conf"
        dest: /etc/squid/squid.conf
        owner: root
        group: root
        mode: '0644'

    - name: Create SSH port forwarding (background process)
      shell: "ssh -fNT -R 3128:127.0.0.1:3128 -i {{ hostvars.target_host.ansible_ssh_private_key_file }} {{ hostvars.target_host.ansible_user }}@{{ hostvars.target_host.ansible_host }}"
      args:
        executable: /bin/bash

- hosts: targets
  gather_facts: no
  become: yes
  tasks:
    - name: Configure apt to use proxy
      copy:
        src: "{{ playbook_dir }}/files/proxy.conf"
        dest: /etc/apt/apt.conf.d/proxy.conf
        owner: root
        group: root
        mode: '0644'
        
    - name: Set proxy environment variables
      shell: "export http_proxy=127.0.0.1:3128 & export https_proxy=127.0.0.1:3128"
